#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=Train_MLP_Pytorch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=02:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm/slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

source deactivate
source activate dl2021

cd /home/lcur0279/projects/DL1Labs/assignment_2_13677640/part1/
echo "Running script on GPU"
srun python -u main_cnn.py --model_name resnet34